# Generated by Django 3.2 on 2023-06-11 12:14

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.IntegerField(verbose_name='Код поставщика')),
                ('internal_code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Код в приложении')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Вегетарианское меню')),
                ('is_special', models.BooleanField(default=False, verbose_name='Специальное предложение')),
                ('is_publish', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('name_ru', core.fields.NamedCharField(max_length=255, verbose_name='Название на русском')),
                ('description_ru', core.fields.CustomCharField(blank=True, max_length=255, null=True, verbose_name='Описание на русском')),
                ('description_en', core.fields.CustomCharField(blank=True, max_length=255, null=True, verbose_name='Описание на английском')),
                ('description_ch', core.fields.CustomCharField(blank=True, max_length=255, null=True, verbose_name='Описание на китайском')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name_ru', core.fields.NamedCharField(max_length=255, unique=True, verbose_name='Название на русском')),
                ('name_en', core.fields.CustomCharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название на английском')),
                ('name_ch', core.fields.CustomCharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название на китайском')),
                ('order_id', models.SmallIntegerField(blank=True, default=10, null=True)),
            ],
            options={
                'verbose_name': 'Раздел меню',
                'verbose_name_plural': 'Разделы меню',
                'ordering': ('name_ru', 'order_id'),
            },
        ),
        migrations.CreateModel(
            name='FoodRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm', models.ForeignKey(db_column='from_food_id', on_delete=django.db.models.deletion.CASCADE, related_name='to_food_id', to='food.food')),
                ('to', models.ForeignKey(db_column='to_food_id', on_delete=django.db.models.deletion.CASCADE, related_name='from_food_id', to='food.food', verbose_name='Дополнительные товары')),
            ],
            options={
                'db_table': 'food_food_additional',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='additional',
            field=models.ManyToManyField(blank=True, through='food.FoodRelationship', to='food.Food', verbose_name='Дополнительные товары'),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='food.foodcategory', verbose_name='Раздел меню'),
        ),
        migrations.AddConstraint(
            model_name='foodrelationship',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, frm=django.db.models.expressions.F('to')), name='self_additional'),
        ),
        migrations.AddConstraint(
            model_name='foodrelationship',
            constraint=models.UniqueConstraint(fields=('frm', 'to'), name='unique_additional'),
        ),
    ]
