# Generated by Django 3.2 on 2023-06-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrelationship',
            name='frm',
            field=models.ForeignKey(db_column='from_food_id', on_delete=django.db.models.deletion.CASCADE, related_name='to_food_id', to='food.food'),
        ),
        migrations.AlterField(
            model_name='foodrelationship',
            name='to',
            field=models.ForeignKey(db_column='to_food_id', on_delete=django.db.models.deletion.CASCADE, related_name='from_food_id', to='food.food'),
        ),
        migrations.AlterModelTable(
            name='foodrelationship',
            table='food_food_additional',
        ),
    ]
