name: Test For UTF

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "lilchiken" --password-stdin
        docker image build -t lilchiken/test-for-utf:latest .
        docker push lilchiken/test-for-utf:latest